### PR TITLE
Attempted test case

### PR DESCRIPTION
**Pull request by dmlap**
I tried to create a test case that would demonstrate the rewind issue before and after https://github.com/brightcove/videojs-overlay/pull/14. This test seems right to me but it passes in both cases. @Kreozot do you have any idea what I'm missing here?

### CODE REVIEW

**Comment by Kreozot** [comment]
It's strange because I tried it out and the test has failed. Is it possible that you forgot to write your test when you checked out to old branch?

**Comment by Kreozot** [comment]
Make sure in both cases exactly 50 assertions passed.

**Comment by dmlap** [comment]
Huh, I must have screwed up checking out the old version last time. The test seems to be working after the change and failing before now to me.

**Comment by Kreozot** [comment]
Seems like you can merge my pull request #14 now :)

**Pull request merged**
